// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hackmessage.proto

#ifndef PROTOBUF_hackmessage_2eproto__INCLUDED
#define PROTOBUF_hackmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_hackmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsTextMsgImpl();
void InitDefaultsTextMsg();
void InitDefaultsStatusMsgImpl();
void InitDefaultsStatusMsg();
void InitDefaultsPackageImpl();
void InitDefaultsPackage();
void InitDefaultsPackageListImpl();
void InitDefaultsPackageList();
inline void InitDefaults() {
  InitDefaultsTextMsg();
  InitDefaultsStatusMsg();
  InitDefaultsPackage();
  InitDefaultsPackageList();
}
}  // namespace protobuf_hackmessage_2eproto
namespace hackchat {
class Package;
class PackageDefaultTypeInternal;
extern PackageDefaultTypeInternal _Package_default_instance_;
class PackageList;
class PackageListDefaultTypeInternal;
extern PackageListDefaultTypeInternal _PackageList_default_instance_;
class StatusMsg;
class StatusMsgDefaultTypeInternal;
extern StatusMsgDefaultTypeInternal _StatusMsg_default_instance_;
class TextMsg;
class TextMsgDefaultTypeInternal;
extern TextMsgDefaultTypeInternal _TextMsg_default_instance_;
}  // namespace hackchat
namespace hackchat {

enum StatusMsg_Status {
  StatusMsg_Status_AUTH_SUCCESS = 0,
  StatusMsg_Status_WRONG_PASS = 1,
  StatusMsg_Status_LOGIN_NOT_FOUND = 2,
  StatusMsg_Status_CONNECTED = 3,
  StatusMsg_Status_DISCONNECTED = 4,
  StatusMsg_Status_NEW_USER = 5,
  StatusMsg_Status_StatusMsg_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StatusMsg_Status_StatusMsg_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StatusMsg_Status_IsValid(int value);
const StatusMsg_Status StatusMsg_Status_Status_MIN = StatusMsg_Status_AUTH_SUCCESS;
const StatusMsg_Status StatusMsg_Status_Status_MAX = StatusMsg_Status_NEW_USER;
const int StatusMsg_Status_Status_ARRAYSIZE = StatusMsg_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* StatusMsg_Status_descriptor();
inline const ::std::string& StatusMsg_Status_Name(StatusMsg_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    StatusMsg_Status_descriptor(), value);
}
inline bool StatusMsg_Status_Parse(
    const ::std::string& name, StatusMsg_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StatusMsg_Status>(
    StatusMsg_Status_descriptor(), name, value);
}
// ===================================================================

class TextMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hackchat.TextMsg) */ {
 public:
  TextMsg();
  virtual ~TextMsg();

  TextMsg(const TextMsg& from);

  inline TextMsg& operator=(const TextMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TextMsg(TextMsg&& from) noexcept
    : TextMsg() {
    *this = ::std::move(from);
  }

  inline TextMsg& operator=(TextMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TextMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TextMsg* internal_default_instance() {
    return reinterpret_cast<const TextMsg*>(
               &_TextMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TextMsg* other);
  friend void swap(TextMsg& a, TextMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TextMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  TextMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TextMsg& from);
  void MergeFrom(const TextMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TextMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg_text = 1;
  void clear_msg_text();
  static const int kMsgTextFieldNumber = 1;
  const ::std::string& msg_text() const;
  void set_msg_text(const ::std::string& value);
  #if LANG_CXX11
  void set_msg_text(::std::string&& value);
  #endif
  void set_msg_text(const char* value);
  void set_msg_text(const char* value, size_t size);
  ::std::string* mutable_msg_text();
  ::std::string* release_msg_text();
  void set_allocated_msg_text(::std::string* msg_text);

  // bool is_feature = 2;
  void clear_is_feature();
  static const int kIsFeatureFieldNumber = 2;
  bool is_feature() const;
  void set_is_feature(bool value);

  // @@protoc_insertion_point(class_scope:hackchat.TextMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_text_;
  bool is_feature_;
  mutable int _cached_size_;
  friend struct ::protobuf_hackmessage_2eproto::TableStruct;
  friend void ::protobuf_hackmessage_2eproto::InitDefaultsTextMsgImpl();
};
// -------------------------------------------------------------------

class StatusMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hackchat.StatusMsg) */ {
 public:
  StatusMsg();
  virtual ~StatusMsg();

  StatusMsg(const StatusMsg& from);

  inline StatusMsg& operator=(const StatusMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusMsg(StatusMsg&& from) noexcept
    : StatusMsg() {
    *this = ::std::move(from);
  }

  inline StatusMsg& operator=(StatusMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusMsg* internal_default_instance() {
    return reinterpret_cast<const StatusMsg*>(
               &_StatusMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(StatusMsg* other);
  friend void swap(StatusMsg& a, StatusMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  StatusMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StatusMsg& from);
  void MergeFrom(const StatusMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StatusMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef StatusMsg_Status Status;
  static const Status AUTH_SUCCESS =
    StatusMsg_Status_AUTH_SUCCESS;
  static const Status WRONG_PASS =
    StatusMsg_Status_WRONG_PASS;
  static const Status LOGIN_NOT_FOUND =
    StatusMsg_Status_LOGIN_NOT_FOUND;
  static const Status CONNECTED =
    StatusMsg_Status_CONNECTED;
  static const Status DISCONNECTED =
    StatusMsg_Status_DISCONNECTED;
  static const Status NEW_USER =
    StatusMsg_Status_NEW_USER;
  static inline bool Status_IsValid(int value) {
    return StatusMsg_Status_IsValid(value);
  }
  static const Status Status_MIN =
    StatusMsg_Status_Status_MIN;
  static const Status Status_MAX =
    StatusMsg_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    StatusMsg_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return StatusMsg_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return StatusMsg_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return StatusMsg_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string user_login = 3;
  void clear_user_login();
  static const int kUserLoginFieldNumber = 3;
  const ::std::string& user_login() const;
  void set_user_login(const ::std::string& value);
  #if LANG_CXX11
  void set_user_login(::std::string&& value);
  #endif
  void set_user_login(const char* value);
  void set_user_login(const char* value, size_t size);
  ::std::string* mutable_user_login();
  ::std::string* release_user_login();
  void set_allocated_user_login(::std::string* user_login);

  // string user_pass = 4;
  void clear_user_pass();
  static const int kUserPassFieldNumber = 4;
  const ::std::string& user_pass() const;
  void set_user_pass(const ::std::string& value);
  #if LANG_CXX11
  void set_user_pass(::std::string&& value);
  #endif
  void set_user_pass(const char* value);
  void set_user_pass(const char* value, size_t size);
  ::std::string* mutable_user_pass();
  ::std::string* release_user_pass();
  void set_allocated_user_pass(::std::string* user_pass);

  // .hackchat.StatusMsg.Status status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::hackchat::StatusMsg_Status status() const;
  void set_status(::hackchat::StatusMsg_Status value);

  // int32 user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::int32 user_id() const;
  void set_user_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hackchat.StatusMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_login_;
  ::google::protobuf::internal::ArenaStringPtr user_pass_;
  int status_;
  ::google::protobuf::int32 user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_hackmessage_2eproto::TableStruct;
  friend void ::protobuf_hackmessage_2eproto::InitDefaultsStatusMsgImpl();
};
// -------------------------------------------------------------------

class Package : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hackchat.Package) */ {
 public:
  Package();
  virtual ~Package();

  Package(const Package& from);

  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Package(Package&& from) noexcept
    : Package() {
    *this = ::std::move(from);
  }

  inline Package& operator=(Package&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Package& default_instance();

  enum MsgCase {
    kTextMsg = 3,
    kStatusMsg = 4,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Package* internal_default_instance() {
    return reinterpret_cast<const Package*>(
               &_Package_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Package* other);
  friend void swap(Package& a, Package& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Package* New() const PROTOBUF_FINAL { return New(NULL); }

  Package* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Package* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 sender_id = 1;
  void clear_sender_id();
  static const int kSenderIdFieldNumber = 1;
  ::google::protobuf::int32 sender_id() const;
  void set_sender_id(::google::protobuf::int32 value);

  // int32 host_id = 2;
  void clear_host_id();
  static const int kHostIdFieldNumber = 2;
  ::google::protobuf::int32 host_id() const;
  void set_host_id(::google::protobuf::int32 value);

  // .hackchat.TextMsg text_msg = 3;
  bool has_text_msg() const;
  void clear_text_msg();
  static const int kTextMsgFieldNumber = 3;
  const ::hackchat::TextMsg& text_msg() const;
  ::hackchat::TextMsg* release_text_msg();
  ::hackchat::TextMsg* mutable_text_msg();
  void set_allocated_text_msg(::hackchat::TextMsg* text_msg);

  // .hackchat.StatusMsg status_msg = 4;
  bool has_status_msg() const;
  void clear_status_msg();
  static const int kStatusMsgFieldNumber = 4;
  const ::hackchat::StatusMsg& status_msg() const;
  ::hackchat::StatusMsg* release_status_msg();
  ::hackchat::StatusMsg* mutable_status_msg();
  void set_allocated_status_msg(::hackchat::StatusMsg* status_msg);

  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:hackchat.Package)
 private:
  void set_has_text_msg();
  void set_has_status_msg();

  inline bool has_msg() const;
  void clear_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 sender_id_;
  ::google::protobuf::int32 host_id_;
  union MsgUnion {
    MsgUnion() {}
    ::hackchat::TextMsg* text_msg_;
    ::hackchat::StatusMsg* status_msg_;
  } msg_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_hackmessage_2eproto::TableStruct;
  friend void ::protobuf_hackmessage_2eproto::InitDefaultsPackageImpl();
};
// -------------------------------------------------------------------

class PackageList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hackchat.PackageList) */ {
 public:
  PackageList();
  virtual ~PackageList();

  PackageList(const PackageList& from);

  inline PackageList& operator=(const PackageList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PackageList(PackageList&& from) noexcept
    : PackageList() {
    *this = ::std::move(from);
  }

  inline PackageList& operator=(PackageList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PackageList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PackageList* internal_default_instance() {
    return reinterpret_cast<const PackageList*>(
               &_PackageList_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PackageList* other);
  friend void swap(PackageList& a, PackageList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PackageList* New() const PROTOBUF_FINAL { return New(NULL); }

  PackageList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PackageList& from);
  void MergeFrom(const PackageList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PackageList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hackchat.Package pack = 1;
  int pack_size() const;
  void clear_pack();
  static const int kPackFieldNumber = 1;
  const ::hackchat::Package& pack(int index) const;
  ::hackchat::Package* mutable_pack(int index);
  ::hackchat::Package* add_pack();
  ::google::protobuf::RepeatedPtrField< ::hackchat::Package >*
      mutable_pack();
  const ::google::protobuf::RepeatedPtrField< ::hackchat::Package >&
      pack() const;

  // @@protoc_insertion_point(class_scope:hackchat.PackageList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::hackchat::Package > pack_;
  mutable int _cached_size_;
  friend struct ::protobuf_hackmessage_2eproto::TableStruct;
  friend void ::protobuf_hackmessage_2eproto::InitDefaultsPackageListImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TextMsg

// string msg_text = 1;
inline void TextMsg::clear_msg_text() {
  msg_text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TextMsg::msg_text() const {
  // @@protoc_insertion_point(field_get:hackchat.TextMsg.msg_text)
  return msg_text_.GetNoArena();
}
inline void TextMsg::set_msg_text(const ::std::string& value) {
  
  msg_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hackchat.TextMsg.msg_text)
}
#if LANG_CXX11
inline void TextMsg::set_msg_text(::std::string&& value) {
  
  msg_text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hackchat.TextMsg.msg_text)
}
#endif
inline void TextMsg::set_msg_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hackchat.TextMsg.msg_text)
}
inline void TextMsg::set_msg_text(const char* value, size_t size) {
  
  msg_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hackchat.TextMsg.msg_text)
}
inline ::std::string* TextMsg::mutable_msg_text() {
  
  // @@protoc_insertion_point(field_mutable:hackchat.TextMsg.msg_text)
  return msg_text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TextMsg::release_msg_text() {
  // @@protoc_insertion_point(field_release:hackchat.TextMsg.msg_text)
  
  return msg_text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TextMsg::set_allocated_msg_text(::std::string* msg_text) {
  if (msg_text != NULL) {
    
  } else {
    
  }
  msg_text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg_text);
  // @@protoc_insertion_point(field_set_allocated:hackchat.TextMsg.msg_text)
}

// bool is_feature = 2;
inline void TextMsg::clear_is_feature() {
  is_feature_ = false;
}
inline bool TextMsg::is_feature() const {
  // @@protoc_insertion_point(field_get:hackchat.TextMsg.is_feature)
  return is_feature_;
}
inline void TextMsg::set_is_feature(bool value) {
  
  is_feature_ = value;
  // @@protoc_insertion_point(field_set:hackchat.TextMsg.is_feature)
}

// -------------------------------------------------------------------

// StatusMsg

// .hackchat.StatusMsg.Status status = 1;
inline void StatusMsg::clear_status() {
  status_ = 0;
}
inline ::hackchat::StatusMsg_Status StatusMsg::status() const {
  // @@protoc_insertion_point(field_get:hackchat.StatusMsg.status)
  return static_cast< ::hackchat::StatusMsg_Status >(status_);
}
inline void StatusMsg::set_status(::hackchat::StatusMsg_Status value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:hackchat.StatusMsg.status)
}

// int32 user_id = 2;
inline void StatusMsg::clear_user_id() {
  user_id_ = 0;
}
inline ::google::protobuf::int32 StatusMsg::user_id() const {
  // @@protoc_insertion_point(field_get:hackchat.StatusMsg.user_id)
  return user_id_;
}
inline void StatusMsg::set_user_id(::google::protobuf::int32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:hackchat.StatusMsg.user_id)
}

// string user_login = 3;
inline void StatusMsg::clear_user_login() {
  user_login_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StatusMsg::user_login() const {
  // @@protoc_insertion_point(field_get:hackchat.StatusMsg.user_login)
  return user_login_.GetNoArena();
}
inline void StatusMsg::set_user_login(const ::std::string& value) {
  
  user_login_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hackchat.StatusMsg.user_login)
}
#if LANG_CXX11
inline void StatusMsg::set_user_login(::std::string&& value) {
  
  user_login_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hackchat.StatusMsg.user_login)
}
#endif
inline void StatusMsg::set_user_login(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_login_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hackchat.StatusMsg.user_login)
}
inline void StatusMsg::set_user_login(const char* value, size_t size) {
  
  user_login_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hackchat.StatusMsg.user_login)
}
inline ::std::string* StatusMsg::mutable_user_login() {
  
  // @@protoc_insertion_point(field_mutable:hackchat.StatusMsg.user_login)
  return user_login_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StatusMsg::release_user_login() {
  // @@protoc_insertion_point(field_release:hackchat.StatusMsg.user_login)
  
  return user_login_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StatusMsg::set_allocated_user_login(::std::string* user_login) {
  if (user_login != NULL) {
    
  } else {
    
  }
  user_login_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_login);
  // @@protoc_insertion_point(field_set_allocated:hackchat.StatusMsg.user_login)
}

// string user_pass = 4;
inline void StatusMsg::clear_user_pass() {
  user_pass_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StatusMsg::user_pass() const {
  // @@protoc_insertion_point(field_get:hackchat.StatusMsg.user_pass)
  return user_pass_.GetNoArena();
}
inline void StatusMsg::set_user_pass(const ::std::string& value) {
  
  user_pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hackchat.StatusMsg.user_pass)
}
#if LANG_CXX11
inline void StatusMsg::set_user_pass(::std::string&& value) {
  
  user_pass_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hackchat.StatusMsg.user_pass)
}
#endif
inline void StatusMsg::set_user_pass(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hackchat.StatusMsg.user_pass)
}
inline void StatusMsg::set_user_pass(const char* value, size_t size) {
  
  user_pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hackchat.StatusMsg.user_pass)
}
inline ::std::string* StatusMsg::mutable_user_pass() {
  
  // @@protoc_insertion_point(field_mutable:hackchat.StatusMsg.user_pass)
  return user_pass_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StatusMsg::release_user_pass() {
  // @@protoc_insertion_point(field_release:hackchat.StatusMsg.user_pass)
  
  return user_pass_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StatusMsg::set_allocated_user_pass(::std::string* user_pass) {
  if (user_pass != NULL) {
    
  } else {
    
  }
  user_pass_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_pass);
  // @@protoc_insertion_point(field_set_allocated:hackchat.StatusMsg.user_pass)
}

// -------------------------------------------------------------------

// Package

// int32 sender_id = 1;
inline void Package::clear_sender_id() {
  sender_id_ = 0;
}
inline ::google::protobuf::int32 Package::sender_id() const {
  // @@protoc_insertion_point(field_get:hackchat.Package.sender_id)
  return sender_id_;
}
inline void Package::set_sender_id(::google::protobuf::int32 value) {
  
  sender_id_ = value;
  // @@protoc_insertion_point(field_set:hackchat.Package.sender_id)
}

// int32 host_id = 2;
inline void Package::clear_host_id() {
  host_id_ = 0;
}
inline ::google::protobuf::int32 Package::host_id() const {
  // @@protoc_insertion_point(field_get:hackchat.Package.host_id)
  return host_id_;
}
inline void Package::set_host_id(::google::protobuf::int32 value) {
  
  host_id_ = value;
  // @@protoc_insertion_point(field_set:hackchat.Package.host_id)
}

// .hackchat.TextMsg text_msg = 3;
inline bool Package::has_text_msg() const {
  return msg_case() == kTextMsg;
}
inline void Package::set_has_text_msg() {
  _oneof_case_[0] = kTextMsg;
}
inline void Package::clear_text_msg() {
  if (has_text_msg()) {
    delete msg_.text_msg_;
    clear_has_msg();
  }
}
inline ::hackchat::TextMsg* Package::release_text_msg() {
  // @@protoc_insertion_point(field_release:hackchat.Package.text_msg)
  if (has_text_msg()) {
    clear_has_msg();
      ::hackchat::TextMsg* temp = msg_.text_msg_;
    msg_.text_msg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::hackchat::TextMsg& Package::text_msg() const {
  // @@protoc_insertion_point(field_get:hackchat.Package.text_msg)
  return has_text_msg()
      ? *msg_.text_msg_
      : *reinterpret_cast< ::hackchat::TextMsg*>(&::hackchat::_TextMsg_default_instance_);
}
inline ::hackchat::TextMsg* Package::mutable_text_msg() {
  if (!has_text_msg()) {
    clear_msg();
    set_has_text_msg();
    msg_.text_msg_ = new ::hackchat::TextMsg;
  }
  // @@protoc_insertion_point(field_mutable:hackchat.Package.text_msg)
  return msg_.text_msg_;
}

// .hackchat.StatusMsg status_msg = 4;
inline bool Package::has_status_msg() const {
  return msg_case() == kStatusMsg;
}
inline void Package::set_has_status_msg() {
  _oneof_case_[0] = kStatusMsg;
}
inline void Package::clear_status_msg() {
  if (has_status_msg()) {
    delete msg_.status_msg_;
    clear_has_msg();
  }
}
inline ::hackchat::StatusMsg* Package::release_status_msg() {
  // @@protoc_insertion_point(field_release:hackchat.Package.status_msg)
  if (has_status_msg()) {
    clear_has_msg();
      ::hackchat::StatusMsg* temp = msg_.status_msg_;
    msg_.status_msg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::hackchat::StatusMsg& Package::status_msg() const {
  // @@protoc_insertion_point(field_get:hackchat.Package.status_msg)
  return has_status_msg()
      ? *msg_.status_msg_
      : *reinterpret_cast< ::hackchat::StatusMsg*>(&::hackchat::_StatusMsg_default_instance_);
}
inline ::hackchat::StatusMsg* Package::mutable_status_msg() {
  if (!has_status_msg()) {
    clear_msg();
    set_has_status_msg();
    msg_.status_msg_ = new ::hackchat::StatusMsg;
  }
  // @@protoc_insertion_point(field_mutable:hackchat.Package.status_msg)
  return msg_.status_msg_;
}

inline bool Package::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void Package::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline Package::MsgCase Package::msg_case() const {
  return Package::MsgCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// PackageList

// repeated .hackchat.Package pack = 1;
inline int PackageList::pack_size() const {
  return pack_.size();
}
inline void PackageList::clear_pack() {
  pack_.Clear();
}
inline const ::hackchat::Package& PackageList::pack(int index) const {
  // @@protoc_insertion_point(field_get:hackchat.PackageList.pack)
  return pack_.Get(index);
}
inline ::hackchat::Package* PackageList::mutable_pack(int index) {
  // @@protoc_insertion_point(field_mutable:hackchat.PackageList.pack)
  return pack_.Mutable(index);
}
inline ::hackchat::Package* PackageList::add_pack() {
  // @@protoc_insertion_point(field_add:hackchat.PackageList.pack)
  return pack_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::hackchat::Package >*
PackageList::mutable_pack() {
  // @@protoc_insertion_point(field_mutable_list:hackchat.PackageList.pack)
  return &pack_;
}
inline const ::google::protobuf::RepeatedPtrField< ::hackchat::Package >&
PackageList::pack() const {
  // @@protoc_insertion_point(field_list:hackchat.PackageList.pack)
  return pack_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hackchat

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::hackchat::StatusMsg_Status> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hackchat::StatusMsg_Status>() {
  return ::hackchat::StatusMsg_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hackmessage_2eproto__INCLUDED
